name: Roave Backwards Compatibility Check
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Setup Cachix
        uses: cachix/cachix-action@v13
        with:
          name: opentelemetry
          extraPullNames: nix-shell, php-src-nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Setup Nix magic cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Instantiate Nix develop
        uses: nicknovitski/nix-develop@v1
      - name: Get composer cache directory
        id: composercache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: List PHP installed extensions
        run: php -m
      - name: Update project dependencies
        run: |
          composer update --no-interaction --no-progress --ansi
      - name: Check for BC breaks
        run: composer check-bcs
